# Generated by Django 6.0.2 on 2026-03-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restauranttable_order_is_paid_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_description',
            field=models.TextField(blank=True, help_text='Decorated order description'),
        ),
    ]
